CREATE OR REPLACE FUNCTION ANKA.FN_EFATURA_CHECK (V_FIRMID NUMBER)
   RETURN NUMBER
IS
   Result   NUMBER;
BEGIN
    
    Select EFATURA_STATUS INTO RESULT from ANKA.FIRM_COMPANY WHERE STATUS = 0 AND FIRM_ID = V_FIRMID;

RETURN RESULT;
END FN_EFATURA_CHECK;
/